prog: main.o  Timer.o
	gcc main.o  Timer.o -o -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
main.o: main.c
	gcc -c main.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
Timer.o: Timer.c
	gcc -c Timer.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf


